**<h1 align="center">NumPy Arrays, Dimensions and Indexing</h1>**

## 👨‍💻 About the Author

- **Author:** Muhammad Usman  
- **Role:** Geologist | AI Engineer Learner  
- **Instructor:** Sir Zafar Iqbal  
- **Course:** AI Engineer  
- **Module:** Module 2 - NumPy and Pandas
-------  

## 1. Introduction

NumPy is one of the most important Python libraries for numerical computing, 
data science, machine learning and artificial intelligence.

It provides powerful multidimensional arrays and mathematical operations.

## 2. Learning Objectives

In this notebook, we will learn:

- NumPy arrays
- Dimensions of arrays
- Shape of arrays
- Checking dimensions using ndim
- Checking shapes using shape
- Array indexing
- Chain indexing
- Multidimensional indexing
- Concatenation of arrays elements

#### **3. Import NumPy**

In [12]:
# import numpy library
import numpy as np

#### **4. Arrays:**
- An array is a collection of multiple values stored together in an organized way.
- Arrays help us:
    - store large data
    - process data quickly
    - perform mathematical operations easily

In [13]:
# numpy array creation
arr = np.array([10,20, 30, 40])
print(arr)

[10 20 30 40]


### **4. Dimension of an Array**
- Dimension means:
    - how data is organized or how many axes/directions the array has

#### **4.1 Types of Array Dimensions**
##### **i. 0-D Array (Scalar)**
- Single value only

In [14]:
# Dimension of arrays
zero_dim = np.array(101)
print(zero_dim)
print(zero_dim.ndim)

101
0


#### **ii. 1D Array**
- A line of values.

In [15]:
# 1D Array
one_dim = np.array([1,2,3,4,5])
print(one_dim)
print(one_dim.ndim)

[1 2 3 4 5]
1


#### **iii. 2D Array**
- Rows and columns like excel sheet.

In [16]:
# 2D Array
two_dim = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [17]:
print(two_dim)
print("Dimensions:", two_dim.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimensions: 2


#### **iv. 3D Array**
- Stack of tables.

In [18]:
# 3D Array. Stack of Tables
three_dim = np.array([
    [["A", "B", "C"], ["D", "E", "F"], ["G", "H", "I"]],
    [["J", "K", "L"], ["M", "N", "O"], ["P", "Q", "R"]],
    [["S", "T", "U"], ["V", "W", "X"], ["Y", "Z", "0"]]
])

In [19]:
print(three_dim.ndim)
print(three_dim.shape)

3
(3, 3, 3)


#### **5. Understanding Shape**

The shape function tells the size of each dimension.

Examples:

- (3,) → 1D array with 3 elements
- (2,3) → 2 rows and 3 columns
- (2,2,2) → depth, rows, columns

In [20]:
arr = np.array([[[1,2,3,4,5]]]) # Each extra bracket level adds another dimension.
print(arr) # print array
print("Shape of Array: ", arr.ndim) # dimension of array
print("Depth, Row, Column:", arr.shape) # shape of array

[[[1 2 3 4 5]]]
Shape of Array:  3
Depth, Row, Column: (1, 1, 5)


### **6. Chain Indexing vs Multidimensional Indexing in NumPy**
- Both are used to access elements in arrays but they work slightly differently.

#### **1. Chain Indexing**
- Accessing elements/ data step by step.
- Slower and less preferred.

In [21]:
# Chain indexing
print(three_dim[0][0][0]) 
print(three_dim[1][1][1]) 
print(three_dim[2][2][2])

A
N
0


#### **2. Multidimensional Indexing**
- All indexes together directly.
- cleaner, faster, standard NumPy style, memory efficient

In [22]:
# Concatenation and Multidimensional indexing
print(three_dim[0, 2, 0] + three_dim[0, 1, 1] + three_dim[1, 1, 2] + three_dim[1, 0, 2] + 
      three_dim[1, 1, 2] + three_dim[0, 2, 0] + three_dim[2, 2, 0])

GEOLOGY


#### **Chain vs Multidimensional Indexing**

| Chain Indexing | Multidimensional Indexing |
|---|---|
| arr[1][2] | arr[1,2] |
| step-by-step | direct |
| slower | faster |
| less preferred | recommended |

#### **Summary**

In this notebook, we learned:

- NumPy arrays
- Array dimensions
- Shape of arrays
- Checking dimensions using ndim
- Checking shapes using shape
- Indexing in arrays
- Chain indexing
- Concatenation and Multidimensional indexing