**<h1 align = "center"> Numpy Data Types </h1>**

- In numpy every array has a specific `data type` (dtype) that defines: 
    - What kind of values the array stores
    - How much memory each element uses
    - How computations are performed
- Data types are very important because NumPy arrays are designed for:
    - Fast computation
    - Efficient memory usage
    - For large datasets, choosing correct dtype is very important

#### **1. Common NumPy Data Types**
1. interger (int8, int16, int32, int64)
2. float (float16, float32, float64)
3. boolean (bool_)
4. string (str_, <U#)
5. object (object_)

In [2]:
import numpy as np

In [5]:
# default data type is int64
arr = np.array([2, 4, 6, 8, 10])
print(arr)
print("Data Type:", arr.dtype)
print(f"Array uses {arr.nbytes} bytes of memory.")

[ 2  4  6  8 10]
Data Type: int64
Array uses 40 bytes of memory.


#### **2. Specifying Data Type Manually (dtype)**

### 1. Integer Array

In [ ]:
# int32 data type
arr32 = np.array([2, 4, 6, 8, 10], dtype = np.int32)
print(arr32)
print("Data Type:", arr32.dtype)
print(f"Array uses {arr32.nbytes} bytes of memory.")

[ 2  4  6  8 10]
Data Type: int32
Array uses 20 bytes of memory.


In [8]:
# int16 data type
arr16 = np.array([2, 4, 6, 8, 10], dtype = np.int16)
print(arr16)
print("Data Type:", arr16.dtype)
print(f"Array uses {arr16.nbytes} bytes of memory.")

[ 2  4  6  8 10]
Data Type: int16
Array uses 10 bytes of memory.


In [ ]:
# int8 data type 
arr8 = np.array([2, 4, 6, 8, 10], dtype = np.int8)
print(arr8)
print("Data Type:", arr8.dtype)
print(f"Array uses {arr8.nbytes} bytes of memory.")
# We can not use int8 data type for values greater than 127 or less than -128

[ 2  4  6  8 10]
Data Type: int8
Array uses 5 bytes of memory.


### 2. Float Array

In [ ]:
# float array
arr_float = np.array([1.5, 2.5, 3.5, 4.5, 5.5], dtype = np.float32)
print(arr_float)
print("Data Type:", arr_float.dtype)
print(f"Array uses {arr_float.nbytes} bytes of memory.")

[1.5 2.5 3.5 4.5 5.5]
Data Type: float32
Array uses 20 bytes of memory.


In [11]:
# convert int array to float array
arr = np.array([2,4,6,8], dtype = np.float16)
print(arr)
print("Data Type:", arr.dtype)      
print(f"Array uses {arr.nbytes} bytes of memory.")

[2. 4. 6. 8.]
Data Type: float16
Array uses 8 bytes of memory.


### 3. Boolean Array

In [12]:
# convert int array boolean array
arr = np.array([0, 2,4,6,8], dtype = np.bool_)
print(arr)
print("Data Type:", arr.dtype)      
print(f"Array uses {arr.nbytes} bytes of memory.")

[False  True  True  True  True]
Data Type: bool
Array uses 5 bytes of memory.


### 4. String Array

In [14]:
# string array
arr = np.array([2,4,6,8], dtype = np.str_)
print(arr)
print("Data Type:", arr.dtype)      
print(f"Array uses {arr.nbytes} bytes of memory.")

['2' '4' '6' '8']
Data Type: <U1
Array uses 16 bytes of memory.


### 5. Object Array

In [15]:
arr_obj = np.array([2, 4.5, "Hello", True], dtype = np.object_)
print(arr_obj)
print("Data Type:", arr_obj.dtype)
print(f"Array uses {arr_obj.nbytes} bytes of memory.")

[2 4.5 'Hello' True]
Data Type: object
Array uses 32 bytes of memory.


### **3. Type Casting**
- Convert one datatype into another using `.astype()`.

In [ ]:
# convert int array to float array using astype() method
arr = np.array([10, 20, 30, 40])
new_arr = arr.astype(np.float32)
print(new_arr)
print("Data Type:", new_arr.dtype)
print(f"Array uses {new_arr.nbytes} bytes of memory.")

[10. 20. 30. 40.]
Data Type: float32
Array uses 16 bytes of memory.
