**<h1 align = "center"> 𝑵𝒖𝒎𝑷𝒚 𝑹𝒆𝒔𝒉𝒂𝒑𝒆 & 𝑺𝒍𝒊𝒄𝒊𝒏𝒈 𝑨𝒓𝒓𝒂𝒚𝒔 </h1>**

- This help in transforming and manipulation of data.
- This change the number of cols and rows.

In [1]:
# import library
import numpy as np

### 1. Reshape Arrays

In [ ]:
# reshape array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(3, 4) # all elements are used to reshape the array
print(arr.shape)
print(arr)

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# for 12 rows and 1 column
arr = arr.reshape(-1, 1) # -1 means number of rows automatically calculated based on the number of columns
print(arr.shape)
print(arr)

(12, 1)
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [ ]:
# Reshape into 3D Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(3, 2, 2) # reshape into 3 blocks, each block has 2 rows and 2 columns
print(arr.shape)
print(arr)

(3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### **2. Slicing in NumPy**
- Slicing means extracting a portion of an array.
- Syntax: array[start : stop : step]

In [19]:
# basic slicing
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[0]) # first element
print(arr[1 : 4]) # slice from index 1 to index 3 (4 is exclusive)
print(arr[2 : ]) # slice from index 2 to the end of the array

10
[20 30 40]
[30 40 50 60]


#### Step Slicing

In [22]:
# Step Slicing
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1 : 5 : 2]) # slice from index 1 to index 4 with a step of 2 (5 is exclusive)

[20 40]


### Negative Slicing

In [25]:
# Negative Indexing
print(arr[-4:]) # (negative indexing starts from the end of the array)

[30 40 50 60]


### Slicing 2D Arrays

In [32]:
# slicing 2D array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(arr.shape)

(4, 4)


In [30]:
print(arr[0]) # first row

[1 2 3 4]


In [31]:
print(arr[0 : 3]) # slice from index 0 to index 2 (3 is exclusive)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(arr[0 : 3 : 2]) # slice from index 0 to index 2 with a step of 2 (3 is exclusive)

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [34]:
print(arr[1 : 3, 2 : 4]) # slice from index 1 to index 2 (3 is exclusive) and from index 2 to index 3 (4 is exclusive)

[[ 7  8]
 [11 12]]


In [37]:
print(arr[::3]) # slice every 3rd row (0, 3, 6, ...)

[[ 1  2  3  4]
 [13 14 15 16]]


In [39]:
# Reverse order
print(arr[::-1]) # reverse the order of rows

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [40]:
# reverse order of columns
print(arr[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [45]:
# access values
print(arr)
print("Value:", arr[1, 2]) # access the element at row index 1 and column index 2 (7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Value: 7


In [47]:
print(arr[:, 3]) # access the 4th column (index 3) of all rows

[ 4  8 12 16]


In [48]:
print(arr[2, :]) # access the 3rd row (index 2) of all columns

[ 9 10 11 12]
