**<h1 align = "center"> Functions-NumPy </h1>**

### 1. Array Creation Functions
- These are the most commonly used functions.

In [3]:
# create array
import numpy as np
arr = np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


### i. Zeros Array

In [9]:
# zeros array
zeros_arr = np.zeros(10)
print("1D Array:", zeros_arr)
# 2d zeros array
zeros_arr_2d = np.zeros((3, 4)) # rows, columns
print("2D Array:\n", zeros_arr_2d)
# 3d zeros array
zeros_arr_3d = np.zeros((2, 3, 4)) # depth, rows, columns
print("3D Array:\n", zeros_arr_3d)

1D Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2D Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
3D Array:
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### ii. Ones Array

In [13]:
# ones array
ones_arr = np.ones(5)
print("1D Array:", ones_arr)
ones_arr_2d = np.ones((2, 3))
print("2D Array:\n", ones_arr_2d)
ones_arr_3d = np.ones((2, 2, 2))
print("3D Array:\n", ones_arr_3d)

1D Array: [1. 1. 1. 1. 1.]
2D Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
3D Array:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### iii. Arange Function

In [32]:
# arange array
arange_arr = np.arange(0, 10) # start, stop
print("1D Array:", arange_arr)
arange_arr_2d = np.arange(0, 12).reshape(3, 4) # start, stop, reshape to 3 rows and 4 columns
print("2D Array:\n", arange_arr_2d) 
arange_arr_3d = np.arange(0, 24, 3).reshape(2, 2, 2) # start, stop, step, reshape to 2 depth, 2 rows and 2 columns
print("3D Array:\n", arange_arr_3d)

# check number of elements in the arr

1D Array: [0 1 2 3 4 5 6 7 8 9]
2D Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
3D Array:
 [[[ 0  3]
  [ 6  9]]

 [[12 15]
  [18 21]]]


### iv. Linspace Function
- Divide array into parts

In [40]:
# linspae function
linspace_arr = np.linspace(0, 1, 5) # start, stop, number of elements
print("1D Array:", linspace_arr)
linspace_arr_2 = np.linspace(0, 100, 5)
print("2 Array:\n", linspace_arr_2)

1D Array: [0.   0.25 0.5  0.75 1.  ]
2 Array:
 [  0.  25.  50.  75. 100.]


### v. Customized Array

In [41]:
# Customized array
cus_arr = np.full((2, 3), 7) # shape, fill value
print("Customized Array:\n", cus_arr)

Customized Array:
 [[7 7 7]
 [7 7 7]]


### vi. Eye Function-diagonal

In [54]:
# eye array
eye_arr = np.eye(2, 2,) # size of the identity matrix
print("Identity Matrix:\n", eye_arr)

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


## 2. Aggregate Functions
- Summerize data and return a single value.

In [57]:
# sum 
arr = np.array([1,2,3,4])
print("Sum:", np.sum(arr))
# product
print("Product:", np.prod(arr))

Sum: 10
Product: 24


In [58]:
# Cumulative sum
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Cumulative Sum:", np.cumsum(arr))

Cumulative Sum: [ 1  3  6 10 15 21 28 36 45 55]


## 3. Statistical Functions

In [65]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print("Cumulative Product:\n", np.cumprod(arr))
# mean
print("Mean:", np.mean(arr))
# median
print("Median:", np.median(arr))
# standard deviation
print("Standard Deviation:", np.std(arr))
# variance
print("Variance:", np.var(arr)) 
# minimum
print("Minimum:", np.min(arr))
# maximum
print("Maximum:", np.max(arr))  

Cumulative Product:
 [      1       2       6      24     120     720    5040   40320  362880
 3628800]
Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Minimum: 1
Maximum: 10


## 4. Searching Functions
- Used to find position of value

In [66]:
# find the index of the minimum and maximum values
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
print("Index of Minimum:", np.argmin(arr))
print("Index of Maximum:", np.argmax(arr))


Index of Minimum: 1
Index of Maximum: 5


## 5. Adding Rows or Cols of Array

In [68]:
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
print("Adding Cols (0):\n", np.sum(arr, axis=0)) # sum along columns
print("Adding Rows (1):\n", np.sum(arr, axis=1)) # sum along rows

Adding Cols (0):
 [ 7  9 11 13 15]
Adding Rows (1):
 [15 40]
