**<h1 align = "center"> Filtering, Saving and Loading </h1>**

### 1. Filtering
- Process of selecting element from an array that match a given condition.

In [3]:
# import library
import numpy as np
# array
arr = np.array([10,20,30,40,50])
filtered_arr = arr[arr > 25]
print(filtered_arr)
filtered_arr2 = arr[arr < 35]
print(filtered_arr2)

[30 40 50]
[10 20 30]


In [4]:
# High porosity zones
porosity = np.array([5, 7, 8, 9, 10, 12, 15, 20, 24, 25, 28, 30])
# good reservoirs have porosity > 10%
good_zone = porosity[porosity > 10]
print(good_zone)

[12 15 20 24 25 28 30]


In [5]:
# Multiple conditions
porosity = np.array([5, 7, 8, 9, 10, 12, 15, 20, 24, 25, 28, 30])
good_zone_2 = porosity[(porosity >= 10) & (porosity <= 20)]
print(good_zone_2)

[10 12 15 20]


#### 1.1 Filtering 2D Arrays

In [8]:
# well-log data with depth and gamma ray values
logs = np.array([[1000, 45],
                 [1001, 50],
                 [1002, 55],
                 [1003, 60],
                 [1004, 65]])

# filter logs with gamma ray > 55
filtered_logs = logs[logs[:, 1] > 55]
print(filtered_logs)

[[1003   60]
 [1004   65]]


In [9]:
# Returns positions matching a condition.
positions = np.where(logs[:, 1] > 55)
print(positions)

(array([3, 4]),)


### 2. Saving Arrays
- Returns positions matching a condition.

In [15]:
arr1 = np.array([10, 20, 30, 40, 50])
# Locally save array to file
np.save("my_array.npy", arr1)
print("Array saved.....!")

Array saved.....!


In [ ]:
# save with file name and path
np.save("D:\\files\\my_array.npy", arr1)

### 3. Loading Files

In [17]:
loaded_arr = np.load("my_array.npy")
print("Loaded array:", loaded_arr)

Loaded array: [10 20 30 40 50]


### 4. Save Multiple Arrays (np.savez)

In [19]:
depth = np.array([1000, 1001, 1002, 1003, 1004])
porosity = np.array([5, 7, 8, 9, 10])
# Save multiple arrays to a single file
np.savez("well_data.npz", depth, porosity)
print("Multiple arrays saved.....!")

Multiple arrays saved.....!


In [22]:
# load multiple arrays from file
data = np.load("well_data.npz")
print("Loaded depth:", data["arr_0"])
print("Loaded porosity:", data["arr_1"])

Loaded depth: [1000 1001 1002 1003 1004]
Loaded porosity: [ 5  7  8  9 10]


### 5. Compressed File

In [23]:
np.savez_compressed("well_data_compressed.npz", depth, porosity)
print("Compressed file saved.....!")

Compressed file saved.....!


In [26]:
# Load compressed file
compressed_data = np.load("well_data_compressed.npz")
print("Loaded depth from compressed file:", compressed_data["arr_0"])
print("Loaded porosity from compressed file:", compressed_data["arr_1"])

Loaded depth from compressed file: [1000 1001 1002 1003 1004]
Loaded porosity from compressed file: [ 5  7  8  9 10]


### 6. Working with CSV Files

In [28]:
np.savetxt("depth.csv",
           depth,
           delimiter=",",
           header="Depth",)
# load csv file
loaded_depth = np.loadtxt("depth.csv", delimiter=",", skiprows=1)
print("Loaded depth from csv file:", loaded_depth)

Loaded depth from csv file: [1000. 1001. 1002. 1003. 1004.]
